### ISSUE TITLE
Issue loading packages for preprocess_gagp_bcfs_for_ancestral_id.py

### ISSUE THREAD

**Issue by ajdemery93** [harrispopgen/gagp_mut_evol#1]
Hello!

I am having trouble installing the following packages for your preprocess_gagp_bcfs_for_ancestral_id.py
- All the packages that follow "from common import" are not found in my university's site-packages directory for python, and when I try to install them using the following code (for example, using hwe)
pip install hwe --user

I get the following messages:
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)'),)': /simple/hwe/
Could not fetch URL https://pypi.org/simple/hwe/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/hwe/ (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)'),)) - skipping

I have multiple questions. Was there a specific and older python and pip that you used to running your code? I do not see the specific version in your .py script. Then, how did you install your python packages? Was it with the url leading directly to the python package code, rather than through pypi.org? I would appreciate your help! Happy to provide additional context if needed.

**Comment by goldmich** [comment]
Hi! The `common.py` and `common.R` scripts contain objects and methods required for running other scripts in the repo and need to be in the same working directory as `preprocess_gagp_bcfs_for_ancestral_id.py` and others. They're not a formal package installable from `pip`. I ran everything on python 3.7.6. Hope that helps!

**Comment by ajdemery93** [comment]
Thank you so much for the clarification, I realized that the functions were coming from common.py, and the python version clarification is much appreciated!
